import test, { after } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, existsSync, writeFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { makeRepo, cleanupRepos } from "./fixtures/make-repo.mjs";

after(cleanupRepos);

const CLI = resolve(import.meta.dirname, "..", "bin", "repo-rules.mjs");

function run(args, cwd) {
  return execFileSync("node", [CLI, ...args], { cwd, encoding: "utf8" });
}

const PKG = JSON.stringify({ packageManager: "pnpm@9.1.0", scripts: { test: "vitest run" } }, null, 2);

test("scan writes rules.json and the rendered rules directory", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  const out = run(["scan"], root);
  assert.match(out, /2 rules/);
  const rules = JSON.parse(readFileSync(join(root, ".claude", "repo-rules", "rules.json"), "utf8"));
  assert.equal(rules.length, 2);
  assert.ok(existsSync(join(root, ".claude", "rules", "tooling.md")));
});

test("the rendered file carries the frontmatter and the banner", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  const body = readFileSync(join(root, ".claude", "rules", "tooling.md"), "utf8");
  assert.match(body, /^---\n/);
  assert.ok(body.includes("Generated by repo-rules"));
});

test("check reports every rule live on an unchanged tree", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  const out = run(["check"], root);
  assert.match(out, /2 live/);
  assert.match(out, /0 expired/);
});

test("check expires a rule whose evidence disappeared and rewrites the rules directory", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  writeFileSync(join(root, "package.json"), JSON.stringify({ scripts: { test: "vitest run" } }, null, 2));
  const out = run(["check"], root);
  assert.match(out, /1 live/);
  assert.match(out, /1 expired/);
  const rules = JSON.parse(readFileSync(join(root, ".claude", "repo-rules", "rules.json"), "utf8"));
  assert.equal(rules.length, 1);
});

test("check removes a rules file when its whole topic expires", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  rmSync(join(root, "package.json"));
  run(["check"], root);
  assert.equal(existsSync(join(root, ".claude", "rules", "tooling.md")), false);
});

test("scan on a repo that declares nothing says so and writes no rules directory", () => {
  const root = makeRepo();
  const out = run(["scan"], root);
  assert.match(out, /0 rules/);
  assert.equal(existsSync(join(root, ".claude", "rules")), false);
});

test("check on an unscanned repo exits 0 and says nothing was found", () => {
  const root = makeRepo();
  assert.match(run(["check"], root), /no rules/i);
});
