import test, { after } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, existsSync, writeFileSync, rmSync, mkdirSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { makeRepo, cleanupRepos } from "./fixtures/make-repo.mjs";

after(cleanupRepos);

const CLI = resolve(import.meta.dirname, "..", "bin", "repo-rules.mjs");

function run(args, cwd) {
  return execFileSync("node", [CLI, ...args], { cwd, encoding: "utf8" });
}

// For the failure paths: execFileSync throws on a non-zero exit, and the thrown error carries
// stdout/stderr as properties when the child is spawned with encoding "utf8".
function runExpectingFailure(args, cwd) {
  try {
    run(args, cwd);
  } catch (error) {
    if (error.status === undefined) throw error;
    return error;
  }
  throw new Error(`expected "repo-rules ${args.join(" ")}" to exit non-zero`);
}

const PKG = JSON.stringify({ packageManager: "pnpm@9.1.0", scripts: { test: "vitest run" } }, null, 2);

test("scan writes rules.json and the rendered rules directory", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  const out = run(["scan"], root);
  assert.match(out, /2 rules/);
  const rules = JSON.parse(readFileSync(join(root, ".claude", "repo-rules", "rules.json"), "utf8"));
  assert.equal(rules.length, 2);
  assert.ok(existsSync(join(root, ".claude", "rules", "tooling.md")));
});

test("the rendered file carries the frontmatter and the banner", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  const body = readFileSync(join(root, ".claude", "rules", "tooling.md"), "utf8");
  assert.match(body, /^---\n/);
  assert.ok(body.includes("Generated by repo-rules"));
});

test("check reports every rule live on an unchanged tree", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  const out = run(["check"], root);
  assert.match(out, /2 live/);
  assert.match(out, /0 expired/);
});

test("check expires a rule whose evidence disappeared and rewrites the rules directory", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  writeFileSync(join(root, "package.json"), JSON.stringify({ scripts: { test: "vitest run" } }, null, 2));
  const out = run(["check"], root);
  assert.match(out, /1 live/);
  assert.match(out, /1 expired/);
  const rules = JSON.parse(readFileSync(join(root, ".claude", "repo-rules", "rules.json"), "utf8"));
  assert.equal(rules.length, 1);
});

test("check removes a rules file when its whole topic expires", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  rmSync(join(root, "package.json"));
  run(["check"], root);
  assert.equal(existsSync(join(root, ".claude", "rules", "tooling.md")), false);
});

test("a hand-written rules file survives a scan that overwrites nothing else", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  mkdirSync(join(root, ".claude", "rules"), { recursive: true });
  writeFileSync(join(root, ".claude", "rules", "team-conventions.md"), "# ours\n\nHand written.\n");
  const out = run(["scan"], root);
  assert.match(out, /left \.claude\/rules\/team-conventions\.md alone/);
  assert.equal(readFileSync(join(root, ".claude", "rules", "team-conventions.md"), "utf8"), "# ours\n\nHand written.\n");
});

test("a hand-written rules file survives every rule expiring", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  writeFileSync(join(root, ".claude", "rules", "team-conventions.md"), "# ours\n");
  rmSync(join(root, "package.json"));
  run(["check"], root);
  assert.equal(existsSync(join(root, ".claude", "rules", "team-conventions.md")), true);
  assert.equal(existsSync(join(root, ".claude", "rules", "tooling.md")), false);
});

test("a hand-written file occupying a generated name is left alone and reported", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  mkdirSync(join(root, ".claude", "rules"), { recursive: true });
  writeFileSync(join(root, ".claude", "rules", "tooling.md"), "# ours, not yours\n");
  const out = run(["scan"], root);
  assert.match(out, /left \.claude\/rules\/tooling\.md alone/);
  assert.equal(readFileSync(join(root, ".claude", "rules", "tooling.md"), "utf8"), "# ours, not yours\n");
});

test("scan on a repo that declares nothing says so and writes no rules directory", () => {
  const root = makeRepo();
  const out = run(["scan"], root);
  assert.match(out, /0 rules/);
  assert.equal(existsSync(join(root, ".claude", "rules")), false);
});

test("check on an unscanned repo exits 0 and says nothing was found", () => {
  const root = makeRepo();
  assert.match(run(["check"], root), /no rules/i);
});

test("the CLI exits non-zero outside a git repository and writes nothing", () => {
  const dir = mkdtempSync(join(tmpdir(), "repo-rules-nogit-"));
  try {
    const error = runExpectingFailure(["scan"], dir);
    assert.notEqual(error.status, 0);
    assert.match(error.stderr, /not a git repository/);
    assert.equal(existsSync(join(dir, ".claude")), false);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("check expires the CI gate rule only when the cited run step itself changes", () => {
  const workflow =
    "jobs:\n  ci:\n    steps:\n      - run: pnpm lint --max-warnings 0 --cache\n      - run: pnpm typecheck\n      - run: pnpm test\n";
  const root = makeRepo({ files: { ".github/workflows/ci.yml": workflow } });
  run(["scan"], root);

  // The second and third steps change; the cited first step does not. The old, three-command
  // statement would have gone stale here while still reporting live.
  const reordered =
    "jobs:\n  ci:\n    steps:\n      - run: pnpm lint --max-warnings 0 --cache\n      - run: pnpm build\n      - run: pnpm smoke-test\n";
  writeFileSync(join(root, ".github/workflows/ci.yml"), reordered);
  let out = run(["check"], root);
  assert.match(out, /1 live/);
  assert.match(out, /0 expired/);

  // Now the cited line itself is gone: the rule must expire.
  const replaced = "jobs:\n  ci:\n    steps:\n      - run: pnpm build\n      - run: pnpm smoke-test\n";
  writeFileSync(join(root, ".github/workflows/ci.yml"), replaced);
  out = run(["check"], root);
  assert.match(out, /0 live/);
  assert.match(out, /1 expired/);
  assert.match(out, /expired tooling\.ci-gate/);
});

test("check reports a removed file the way it reports a foreign one", () => {
  const root = makeRepo({ files: { "package.json": PKG } });
  run(["scan"], root);
  rmSync(join(root, "package.json"));
  const out = run(["check"], root);
  assert.match(out, /removed \.claude\/rules\/tooling\.md: no longer generated by repo-rules/);
});
