import test from "node:test";
import assert from "node:assert/strict";
import { render } from "../lib/render.mjs";

const rules = [
  {
    id: "testing.location.spec-dir",
    paths: ["src/", "spec/"],
    statement: "Unit tests live in spec/, named <module>_spec.js.",
    source: "observed",
    support: { followed: 14, candidates: 14, authors: 4, dirs: 3 },
    evidence: [{ path: "spec/parse_spec.js", lines: "1-3", quote: "import { suite }" }],
  },
  {
    id: "testing.runner.node-test",
    paths: ["spec/"],
    statement: "Test files use the node:test runner.",
    source: "observed",
    support: { followed: 12, candidates: 12, authors: 3, dirs: 2 },
    evidence: [{ path: "spec/parse_spec.js", lines: "1-1", quote: "node:test" }],
  },
  {
    id: "tooling.package-manager.pnpm",
    paths: [],
    statement: "The package manager is pnpm, pinned in package.json.",
    source: "declared",
    support: { followed: 1, candidates: 1, authors: 1, dirs: 1 },
    evidence: [{ path: "package.json", lines: "4-4", quote: "packageManager" }],
  },
];

test("groups rules into one file per id prefix", () => {
  const files = render(rules);
  assert.deepEqual([...files.keys()].sort(), ["testing.md", "tooling.md"]);
});

test("frontmatter carries the union of the group's paths as globs", () => {
  const body = render(rules).get("testing.md");
  assert.match(body, /^---\n/);
  assert.match(body, /paths:\n {2}- "spec\/\*\*"\n {2}- "src\/\*\*"\n/);
  assert.match(body, /description: /);
});

test("a repo-wide group omits paths so it always applies", () => {
  const body = render(rules).get("tooling.md");
  assert.ok(!body.includes("paths:"));
});

test("each rule renders its statement and its denominator", () => {
  const body = render(rules).get("testing.md");
  assert.ok(body.includes("Unit tests live in spec/, named <module>_spec.js."));
  assert.ok(body.includes("(14 of 14"));
});

test("each rule cites at least one file", () => {
  const body = render(rules).get("testing.md");
  assert.ok(body.includes("spec/parse_spec.js"));
});

test("the output carries the generator banner and no imperatives", () => {
  const body = render(rules).get("testing.md");
  assert.ok(body.includes("Generated by repo-rules"));
  assert.ok(!/\byour?\b/i.test(body.split("---")[2] ?? body));
});

test("a declared rule renders no denominator", () => {
  const body = render(rules).get("tooling.md");
  assert.ok(body.includes("The package manager is pnpm, pinned in package.json."));
  assert.ok(!body.includes("of 1 sites"));
});

test("a path containing a quote stays valid YAML", () => {
  const odd = [{ ...rules[0], id: "odd.one", paths: ['we"ird/'] }];
  const body = render(odd).get("odd.md");
  assert.ok(body.includes('  - "we\\"ird/**"'));
});

test("rendering is deterministic", () => {
  assert.deepEqual([...render(rules)], [...render([...rules].reverse())]);
});
