const BANNER =
  "Generated by repo-rules. Descriptive facts about this codebase, not instructions.\n" +
  "Each statement cites the files it was drawn from; a statement whose citations no longer\n" +
  "hold has expired and should be removed by running the check command.";

function topicOf(rule) {
  return rule.id.split(".")[0];
}

function renderRule(rule) {
  const { followed, candidates } = rule.support ?? {};
  const denominator =
    Number.isFinite(followed) && Number.isFinite(candidates) && candidates > 0
      ? ` (${followed} of ${candidates} sites)`
      : "";
  const cited = rule.evidence.map((e) => `\`${e.path}\``).join(", ");
  return `- ${rule.statement}${denominator}\n  Evidence: ${cited}`;
}

export function render(rules) {
  const groups = new Map();
  for (const rule of rules) {
    const topic = topicOf(rule);
    if (!groups.has(topic)) groups.set(topic, []);
    groups.get(topic).push(rule);
  }

  const files = new Map();
  for (const topic of [...groups.keys()].sort()) {
    const group = [...groups.get(topic)].sort((a, b) => a.id.localeCompare(b.id));
    const paths = [...new Set(group.flatMap((r) => r.paths))].sort();

    const frontmatter = [
      "---",
      `description: Conventions for ${topic} in this repository`,
      ...(paths.length > 0 ? ["paths:", ...paths.map((p) => `  - "${p}**"`)] : []),
      "---",
    ].join("\n");

    const body = [
      frontmatter,
      "",
      `# ${topic} conventions`,
      "",
      BANNER,
      "",
      ...group.map(renderRule),
      "",
    ].join("\n");

    files.set(`${topic}.md`, body);
  }
  return files;
}
