function counted(n, noun) {
  return `${n} ${n === 1 ? noun : `${noun}s`}`;
}

// One place owns the wording, so a deletion, a drop and an expiry are always announced the
// same way whichever command caused them.
export function report(outcome) {
  if (!outcome.found) return ["no rules for this repo; run repo-rules scan"];

  const lines = [];
  for (const name of outcome.foreign) {
    lines.push(`left .claude/rules/${name} alone: it was not generated by repo-rules`);
  }
  for (const name of outcome.removed) {
    lines.push(`removed .claude/rules/${name}: no rule for this topic remains`);
  }
  for (const item of outcome.dropped) lines.push(`dropped ${item.id}: ${item.reasons.join("; ")}`);
  for (const item of outcome.expired) lines.push(`expired ${item.id}: ${item.reason}`);

  if (outcome.command === "scan") {
    lines.push(`scan complete: ${counted(outcome.rules, "rule")}, ${outcome.dropped.length} dropped`);
  } else if (outcome.command === "check") {
    lines.push(`check complete: ${outcome.rules} live, ${outcome.expired.length} expired`);
  } else {
    lines.push(`render complete: ${counted(outcome.rules, "rule")}`);
  }
  return lines;
}
